project:
  type: website

website:
  title: "openbiomechanics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  page-footer:
    background: "#2E5A38"  # Outfield Green
    foreground: "#FDFBF7"  # Cream Text (for readability)
    center: "Grayson Medico | [Link to Data Source](https://github.com/drivelineresearch/openbiomechanics/tree/main)"

format:
  html:
    theme:
      - cosmo  # or any base theme you like
      - custom.scss
    toc: true


